name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.23.5]
        include:
          - os: ubuntu-latest
            ext: ""

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build binary
        run: |
          mkdir -p output
          go build -o output/mira-${{ matrix.os }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2.0.8
        with:
          files: output/mira-${{ matrix.os }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
